name: Build Application

on:
  pull_request:
  workflow_dispatch:
    inputs:
      target:
        description: "Choose build branch"
        required: true
        default: "test-actions"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: BUILD_APP
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target || '' }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: yarn install --frozen-lockfile

      - run: yarn build:package
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
          RENDERER_CONFIG: ${{ secrets.RENDERER_CONFIG }}
